const ADD_USER = "ADD_USER";
const VERIFY_USER = "VERIFY_USER";
const UPDATE_IN_TYPE = "UPDATE_IN_TYPE";
const WATCH_TRAILER = 'WATCH_TRAILER';

module.exports = {
  ADD_USER,
  VERIFY_USER,
  UPDATE_IN_TYPE,
  WATCH_TRAILER,
};
